crimes_in_boston_vertica:
  outputs:
    dev:
      type: vertica
      host: vertica
      port: 5433
      username: dbadmin
      password: v7DlP5C0XT1jJ2HGpoEZciYQoMiP2P0y
      database: boston_crimes
      schema: dbt
  target: dev
