crimes_in_boston_vertica:
  outputs:
    dev:
      type: vertica
      host: 172.17.0.4
      port: 5433
      username: dbadmin
      password: f0QMZXw8RHlZlwamwHQeQS4TDFlVjIcv
      database: boston_crimes
      schema: dbt
  target: dev
